### ISSUE TITLE
README is sort of confusing

### ISSUE THREAD

**Issue by warmwaffles** [pgericson/zendesk-api#17]
I understand what was meant by

``` markdown
For the most part all functions is based on the following functions
REST function_names = %{user, organization, group, ticket,attachement, tag, forum, entries, search}

### Show

    z.get_function_name(user_id)
```

But this took me a few hours of digging around to find out that this is the gem I was looking for. I can fork this and fill the documentation out a little more, because I can't be the only one who has had this issue in the past.

**Comment by pgericson** [comment]
I created a small commit to clear some things up, but you are more than welcome to make the documentation more understandable!

A gem is nothing without some proper documentation.

the commit:
https://github.com/pgericson/zendesk-api/commit/9f961ce0c3e1c10cbdeb1e1884b309d75e74eb62

**Comment by warmwaffles** [comment]
Looks good, I'll see if I can come up with some example code snippets to add in as well

**Comment by pgericson** [comment]
closing this
