### ISSUE TITLE
cannot load such file -- zendesk/api

### ISSUE THREAD

**Issue by awesomelionel** [pgericson/zendesk-api#21]
Ruby -v : 1.9.3-p125 (using rbenv)
Rails -v : 3.2.3

When I run `$ rake -T --trace`, I get the following error:

rake aborted!
cannot load such file -- zendesk/api
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.2.1/lib/bundler/runtime.rb:74:in `require'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.2.1/lib/bundler/runtime.rb:74:in`rescue in block in require'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.2.1/lib/bundler/runtime.rb:62:in `block in require'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.2.1/lib/bundler/runtime.rb:55:in`each'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.2.1/lib/bundler/runtime.rb:55:in `require'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.2.1/lib/bundler.rb:128:in`require'
/vagrant/config/application.rb:7:in `<top (required)>'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/vagrant/Rakefile:5:in`<top (required)>'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rake/rake_module.rb:25:in `load'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rake/rake_module.rb:25:in`load_rakefile'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rake/application.rb:501:in `raw_load_rakefile'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rake/application.rb:82:in`block in load_rakefile'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rake/application.rb:81:in`load_rakefile'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rake/application.rb:65:in `block in run'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rake/application.rb:133:in`standard_exception_handling'
/home/vagrant/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rake/application.rb:63:in `run'
/home/vagrant/.rbenv/versions/1.9.3-p125/bin/rake:32:in`<main>'

The gem is there in my gems folder but bundler can't seem to find it.

**Comment by jordanandree** [comment]
I am having this same issue.

After digging into bundler's `lib/bundler/runtime.rb` files, it looks like it is substituting dashes with forward slashes for file names on lines 74 and 75 ([source](https://github.com/carlhuda/bundler/blob/1-2-stable/lib/bundler/runtime.rb#L73-74)):

```
namespaced_file = dep.name.gsub('-', '/')
Kernel.require namespaced_file
```

I think a solution is to rename the `zendesk-api.rb` file to `zendesk_api.rb` and update where it is being required in the gem. I'm running some tests on this change ... will submit a pull request unless there is a better solution.

**Comment by jordanandree** [comment]
Issued pull request #22 with a tested fix for this
