### ISSUE TITLE
curl.perform never called when searching

### ISSUE THREAD

**Issue by CardboardMechanic** [pgericson/zendesk-api#3]
whenever make_request is called and the body param is not empty, curl.perform is never called, and an error is thrown.

This was discovered when calling search()

**Comment by pgericson** [comment]
Fixed in commit:
http://github.com/pgericson/zendesk-api/commit/66ff289bb5275c1c7b10737792d6c017c460e0b4

And a new version of the gem is up with this fix.  
version 0.2.2
gem pushed to rubygems.org

Code provided by Tildewill, thanks!
